### ISSUE TITLE
uonome is damaged and can't be opend

### ISSUE THREAD

**Issue by ukisoft** [karaage0703/uonome#7]
Hi,

I want to make fisheyed images, so trying uonome.
But when I open uonome v1.2 on mac, there is the massage like below,

```
"uonome" is damaged and can't be opened. You should move it to the Trash.
```

My mac os is Mojave 10.14.5.
How can I use uonome?

And, additionally, I want to use uonome by cli.
Is it possible?

Thank you :)

**Comment by karaage0703** [comment]
Hi, @ukisoft san
Binary app is option. If you want to use uonome, please download Processing and copy code and run.
Maybe you can export binary app for your environment.

**Comment by ukisoft** [comment]
It works, amazing!
Thank you :)
