### ISSUE TITLE
MacBook Pro2021 16インチでアプリを開くと、壊れているため開けませんという表示が出る

### ISSUE THREAD

**Issue by ghost** [karaage0703/uonome#8]
<img width="258" alt="スクリーンショット 2023-09-09 15 39 55" src="https://github.com/karaage0703/uonome/assets/31416292/bfe5cb05-343f-4402-bcaf-2cdd3800cd69">

**Comment by karaage0703** [comment]
Googleで調べてみたりすると良いかもです。

https://knowledge.shade3d.jp/knowledgebase/%E3%80%8C%E5%A3%8A%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%81%9F%E3%82%81%E9%96%8B%E3%81%91%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82%E3%82%B4%E3%83%9F%E7%AE%B1%E3%81%AB%E5%85%A5%E3%82%8C%E3%82%8B%E5%BF%85
